export const SUB_EVENT_NAME = {
  SENT_MESSAGE: "SENT_MESSAGE",
  UPDATE_CONVERSATION: "UPDATE_CONVERSATION",
};

export const ACTION_UPDATE_CONVERSATION = {
  SENT_MESSAGE: "SENT_MESSAGE",
  MARK_READ: "MARK_READ",
};
